"""Static metadata extracted from the 29 historical cleanup assertions."""

PROFILES = {
    'acceptance-retirement': {
        'source': '.cache/acceptance-retirement-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'B',
        'trace': None,
    },
    'browser-finish-retirement': {
        'source': '.cache/browser-finish-retirement-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'B',
        'trace': None,
    },
    'controller-workflow-span': {
        'explicit_project_regex': r'antnest-workflow-tests-[0-9]+',
        'source': '.cache/controller-workflow-span-20260921/check-cleanup.py',
        'schema': 'lower5-sorted',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'identity',
        'project_glob': '*docker*.log',
        'project_regex': r'antnest-lifecycle-[a-f0-9]{8}',
        'required_logs': [],
        'required_projects': 3,
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'final-regression': {
        'source': '.cache/final-regression-20260922/final-environment.py',
        'schema': 'upper9-final-raw',
        'baseline': 'retained-before.json',
        'report': 'final-environment.json',
        'result': 'final',
        'required_logs': [],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'identity-migration': {
        'source': '.cache/identity-migration-20260917/check-cleanup.py',
        'schema': 'lower4-sorted',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'identity',
        'project_glob': '*docker*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'interruption-assets-retirement': {
        'source': '.cache/interruption-assets-retirement-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'B',
        'trace': None,
    },
    'legacy-acceptance/base': {
        'source': '.cache/legacy-acceptance-20260917/base-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'base-retained-before.json',
        'report': 'base-cleanup.json',
        'result': 'legacy',
        'project_glob': 'base-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-stage3-local',
        'legacy_prefix': 'base-docker-',
        'trace': None,
    },
    'legacy-acceptance/cost': {
        'source': '.cache/legacy-acceptance-20260917/cost-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'cost-retained-before.json',
        'report': 'cost-cleanup.json',
        'result': 'legacy',
        'project_glob': 'cost-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-session-cost',
        'legacy_prefix': 'cost-docker-',
        'trace': None,
    },
    'legacy-acceptance/managed': {
        'source': '.cache/legacy-acceptance-20260917/managed-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'managed-retained-before.json',
        'report': 'managed-cleanup.json',
        'result': 'legacy',
        'project_glob': 'managed-v*-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-managed-mcp-v[12]',
        'legacy_prefix': 'managed-v[12]-docker-',
        'trace': None,
    },
    'legacy-acceptance/persistence': {
        'source': '.cache/legacy-acceptance-20260917/persistence-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'rpc-retained-before.json',
        'report': 'persistence-cleanup.json',
        'result': 'legacy',
        'project_glob': 'persistence-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-acp-persistence',
        'legacy_prefix': 'persistence-docker-',
        'trace': None,
    },
    'legacy-acceptance/restart': {
        'source': '.cache/legacy-acceptance-20260917/restart-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'rpc-retained-before.json',
        'report': 'restart-cleanup.json',
        'result': 'legacy',
        'project_glob': 'restart-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-acp-restart',
        'legacy_prefix': 'restart-docker-',
        'trace': None,
    },
    'legacy-acceptance/rpc': {
        'source': '.cache/legacy-acceptance-20260917/rpc-cleanup-check.py',
        'schema': 'lower4-ordered',
        'baseline': 'rpc-retained-before.json',
        'report': 'rpc-cleanup.json',
        'result': 'legacy',
        'project_glob': 'rpc-docker-*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': True,
        'scope_only': False,
        'process': 'Legacy',
        'legacy_mode': 'e2e-rpc-response-loss',
        'legacy_prefix': 'rpc-docker-',
        'trace': None,
    },
    'legacy-closeout': {
        'source': '.cache/legacy-closeout-20260921/check-cleanup.py',
        'schema': 'lower5-sorted',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'identity',
        'project_glob': '*docker*.log',
        'project_regex': r'antnest-stage3-e2e-\d+',
        'required_logs': [],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'lifecycle-foundation': {
        'source': '.cache/lifecycle-foundation-20260921/check-cleanup.py',
        'schema': 'lower5-sorted',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'identity',
        'project_glob': '*docker*.log',
        'project_regex': r'antnest-lifecycle-[a-f0-9]{8}',
        'required_logs': [],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'lifecycle-interrupted-migration': {
        'source': '.cache/lifecycle-interrupted-migration-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'Disposable foundation project: (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'I',
        'trace': None,
    },
    'lifecycle-loss-migration': {
        'explicit_project_regex': r'antnest-lifecycle-[a-f0-9]{8}',
        'source': '.cache/lifecycle-loss-migration-20260921/verify-cleanup.py',
        'schema': 'lower6-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'selected',
        'required_logs': [],
        'required_projects': 3,
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'R',
        'trace': None,
    },
    'lifecycle-network-migration': {
        'trace_project_log': 'docker-2.log',
        'source': '.cache/lifecycle-network-migration-20260921/check-cleanup.py',
        'schema': 'lower6-all',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'network',
        'required_logs': ['docker-1.log', 'docker-2.log', 'foundation-regression.log'],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'N',
        'trace': 'network',
    },
    'lifecycle-restore-migration': {
        'explicit_project_regex': r'antnest-lifecycle-[a-f0-9]{8}',
        'source': '.cache/lifecycle-restore-migration-20260921/verify-cleanup.py',
        'schema': 'lower6-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'selected',
        'required_logs': [],
        'required_projects': 2,
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'R',
        'trace': None,
    },
    'lifecycle-shutdown-migration': {
        'trace_project_log': 'docker-3.log',
        'source': '.cache/lifecycle-shutdown-migration-20260921/check-cleanup.py',
        'schema': 'lower6-all',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'shutdown',
        'required_logs': ['docker-1.log', 'docker-2.log', 'docker-3.log', 'docker-4.log'],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'N',
        'trace': 'shutdown',
    },
    'recovery-support-split': {
        'source': '.cache/recovery-support-split-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'B',
        'trace': None,
    },
    'retained-seed-retirement': {
        'source': '.cache/retained-seed-retirement-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'antnest-stage3-e2e-[0-9]+',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'T',
        'trace': None,
    },
    'runtime-crash-integration': {
        'source': '.cache/runtime-crash-integration-20260922/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'K',
        'trace': None,
    },
    'runtime-crash-recovery': {
        'source': '.cache/runtime-crash-recovery-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'crash',
        'project_glob': 'component-*.log',
        'project_regex': r'Disposable crash component scope: (antnest-rc-crash-[a-f0-9]{16})',
        'required_logs': [],
        'project_report': 'postgres-cleanup.json',
        'require_projects': False,
        'resource_names': False,
        'scope_only': True,
        'process': 'G',
        'trace': None,
    },
    'runtime-inspect-absence': {
        'source': '.cache/runtime-inspect-absence-20260921/verify-cleanup.py',
        'schema': 'lower6-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'selected',
        'project_regex': r'Disposable foundation project: (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': ['loss.log', 'foundation.log'],
        'project_report': 'service-cleanup.json',
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'RI',
        'trace': None,
    },
    'stage3-tail-retirement': {
        'source': '.cache/stage3-tail-retirement-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'antnest-stage3-e2e-[0-9]+',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'T',
        'trace': None,
    },
    'temporal-readiness': {
        'source': '.cache/temporal-readiness-20260921/check-cleanup.py',
        'schema': 'lower6-all',
        'baseline': 'retained-before.json',
        'report': 'summary.json',
        'result': 'temporal',
        'required_logs': ['shutdown-1.log', 'shutdown-2.log', 'foundation.log'],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': 'H',
        'trace': 'temporal',
    },
    'timeout-failure-followup': {
        'source': '.cache/timeout-failure-followup-20260922/final-environment.py',
        'schema': 'upper9-final-normalized',
        'baseline': 'retained-before.json',
        'report': 'final-environment.json',
        'result': 'final',
        'required_logs': [],
        'require_projects': False,
        'resource_names': False,
        'scope_only': False,
        'process': None,
        'trace': None,
    },
    'workspace-browser-migration': {
        'source': '.cache/workspace-browser-migration-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'(?:Disposable foundation project|C4 disposable project): (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'WBrowser',
        'trace': None,
    },
    'workspace-protocol-migration': {
        'source': '.cache/workspace-protocol-migration-20260921/cleanup.py',
        'schema': 'upper9-selected',
        'baseline': 'retained-before.json',
        'report': 'cleanup.json',
        'result': 'retirement',
        'project_glob': 'docker*.log',
        'project_regex': r'Disposable foundation project: (antnest-lifecycle-[a-f0-9]{8})',
        'required_logs': [],
        'require_projects': True,
        'resource_names': False,
        'scope_only': False,
        'process': 'WProtocol',
        'trace': None,
    },
}
