package domain

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"slices"
	"time"
)

const LearningAutomatic = "automatic"
const LearningOff = "off"

var learningIdentity = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]{0,199}$`)
var learningPackagePath = regexp.MustCompile(`^\.antnest/skills/[a-z0-9]+(-[a-z0-9]+)*$`)
var learningRevision = regexp.MustCompile(`^[0-9a-f]{64}$`)

type SkillLearningScope struct {
	AutoGeneratedPersonal bool     `json:"auto_generated_personal"`
	AdoptedPaths          []string `json:"adopted_paths"`
}

type SkillLearningLimits struct {
	DailyReviews           int `json:"daily_reviews"`
	DailyModelInputTokens  int `json:"daily_model_input_tokens"`
	DailyModelOutputTokens int `json:"daily_model_output_tokens"`
}

type SkillLearningPolicy struct {
	OrganizationID   string              `json:"organization_id"`
	AgentID          string              `json:"agent_id"`
	OwnerPrincipalID string              `json:"owner_principal_id"`
	Revision         string              `json:"revision"`
	Mode             string              `json:"mode"`
	Scope            SkillLearningScope  `json:"scope"`
	PinnedPaths      []string            `json:"pinned_paths"`
	Limits           SkillLearningLimits `json:"limits"`
	ActivationCutAt  time.Time           `json:"activation_cut_at"`
}

func DefaultSkillLearningPolicy(organizationID, agentID, ownerID string, activationCut time.Time) SkillLearningPolicy {
	policy := SkillLearningPolicy{
		OrganizationID: organizationID, AgentID: agentID, OwnerPrincipalID: ownerID,
		Mode:            LearningAutomatic,
		Scope:           SkillLearningScope{AutoGeneratedPersonal: true, AdoptedPaths: []string{}},
		PinnedPaths:     []string{},
		Limits:          SkillLearningLimits{DailyReviews: 20, DailyModelInputTokens: 320000, DailyModelOutputTokens: 80000},
		ActivationCutAt: activationCut.UTC().Truncate(time.Microsecond),
	}
	policy.Revision, _ = policy.RevisionForSequence(1)
	return policy
}

func (policy SkillLearningPolicy) Validate() error {
	if !learningRevision.MatchString(policy.Revision) {
		return fmt.Errorf("invalid learning policy revision")
	}
	if policy.ActivationCutAt.IsZero() {
		return fmt.Errorf("missing learning policy activation cut")
	}
	return policy.ValidateMutation()
}

func (policy SkillLearningPolicy) ValidateMutation() error { return policy.validateContent() }

func (policy SkillLearningPolicy) validateContent() error {
	if !learningIdentity.MatchString(policy.OrganizationID) || !learningIdentity.MatchString(policy.AgentID) ||
		!learningIdentity.MatchString(policy.OwnerPrincipalID) ||
		(policy.Mode != LearningAutomatic && policy.Mode != LearningOff) {
		return fmt.Errorf("invalid learning policy identity or mode")
	}
	if err := validateLearningPaths(policy.Scope.AdoptedPaths); err != nil {
		return err
	}
	if len(policy.Scope.AdoptedPaths) != 0 {
		return fmt.Errorf("adoption of existing personal Skills is not enabled in v1")
	}
	if err := validateLearningPaths(policy.PinnedPaths); err != nil {
		return err
	}
	if policy.Limits.DailyReviews < 0 || policy.Limits.DailyReviews > 20 ||
		policy.Limits.DailyModelInputTokens < 0 || policy.Limits.DailyModelInputTokens > 320000 ||
		policy.Limits.DailyModelOutputTokens < 0 || policy.Limits.DailyModelOutputTokens > 80000 {
		return fmt.Errorf("learning policy budget exceeds v1 ceiling")
	}
	return nil
}

func validateLearningPaths(paths []string) error {
	if paths == nil || len(paths) > 32 || !slices.IsSorted(paths) {
		return fmt.Errorf("learning policy paths must be a sorted bounded array")
	}
	for index, path := range paths {
		if len(path) > 96 || !learningPackagePath.MatchString(path) || index > 0 && paths[index-1] == path {
			return fmt.Errorf("invalid or duplicate learning policy path")
		}
	}
	return nil
}

func (policy SkillLearningPolicy) RevisionForSequence(sequence uint64) (string, error) {
	if sequence == 0 {
		return "", fmt.Errorf("learning policy sequence must be positive")
	}
	if err := policy.validateContent(); err != nil {
		return "", err
	}
	if policy.ActivationCutAt.IsZero() {
		return "", fmt.Errorf("missing learning policy activation cut")
	}
	encoded, err := json.Marshal(struct {
		Sequence uint64              `json:"sequence"`
		Policy   SkillLearningPolicy `json:"policy"`
	}{Sequence: sequence, Policy: SkillLearningPolicy{
		OrganizationID: policy.OrganizationID, AgentID: policy.AgentID, OwnerPrincipalID: policy.OwnerPrincipalID,
		Mode: policy.Mode, Scope: policy.Scope, PinnedPaths: policy.PinnedPaths, Limits: policy.Limits,
	}})
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:]), nil
}
