package domain

import (
	"testing"
	"time"
)

func TestDefaultSkillLearningPolicyIsBoundedAndAutomatic(t *testing.T) {
	policy := DefaultSkillLearningPolicy("org-1", "agent-1", "owner-1", time.Unix(1, 0))
	if err := policy.Validate(); err != nil {
		t.Fatal(err)
	}
	if policy.Mode != LearningAutomatic || !policy.Scope.AutoGeneratedPersonal || len(policy.Scope.AdoptedPaths) != 0 ||
		policy.Limits.DailyReviews != 20 || policy.Limits.DailyModelInputTokens != 320000 || policy.Limits.DailyModelOutputTokens != 80000 {
		t.Fatalf("unsafe default learning policy: %+v", policy)
	}
}

func TestSkillLearningPolicyRejectsInvalidPathsAndBudgets(t *testing.T) {
	base := DefaultSkillLearningPolicy("org-1", "agent-1", "owner-1", time.Unix(1, 0))
	checks := []struct {
		name string
		edit func(*SkillLearningPolicy)
	}{
		{"unknown mode", func(p *SkillLearningPolicy) { p.Mode = "manual" }},
		{"absolute adopted path", func(p *SkillLearningPolicy) { p.Scope.AdoptedPaths = []string{"/workspace/.antnest/skills/a"} }},
		{"traversal adopted path", func(p *SkillLearningPolicy) { p.Scope.AdoptedPaths = []string{".antnest/skills/../a"} }},
		{"duplicate adopted path", func(p *SkillLearningPolicy) {
			p.Scope.AdoptedPaths = []string{".antnest/skills/a", ".antnest/skills/a"}
		}},
		{"unsorted pinned paths", func(p *SkillLearningPolicy) { p.PinnedPaths = []string{".antnest/skills/z", ".antnest/skills/a"} }},
		{"excess review budget", func(p *SkillLearningPolicy) { p.Limits.DailyReviews = 21 }},
		{"negative token budget", func(p *SkillLearningPolicy) { p.Limits.DailyModelInputTokens = -1 }},
		{"wrong owner", func(p *SkillLearningPolicy) { p.OwnerPrincipalID = "" }},
	}
	for _, check := range checks {
		t.Run(check.name, func(t *testing.T) {
			candidate := base
			check.edit(&candidate)
			if err := candidate.Validate(); err == nil {
				t.Fatalf("invalid policy accepted: %+v", candidate)
			}
		})
	}
}

func TestSkillLearningPolicyRevisionUsesIndependentSequence(t *testing.T) {
	policy := DefaultSkillLearningPolicy("org-1", "agent-1", "owner-1", time.Unix(1, 0))
	first, err := policy.RevisionForSequence(1)
	if err != nil {
		t.Fatal(err)
	}
	second, err := policy.RevisionForSequence(2)
	if err != nil || first == second || len(first) != 64 || len(second) != 64 {
		t.Fatalf("independent revision failed: %q %q %v", first, second, err)
	}
	if _, err := policy.RevisionForSequence(0); err == nil {
		t.Fatal("zero policy sequence accepted")
	}
}
