package application

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"slices"
	"strings"

	"soft/antnest-platform/services/agent-controller/internal/domain"
	"soft/antnest-platform/services/agent-controller/internal/ports"
)

var learningRequestID = regexp.MustCompile(`^[!-~]{1,128}$`)
var learningExpectedRevision = regexp.MustCompile(`^[0-9a-f]{64}$`)

type SkillLearningPolicyService struct {
	store      ports.SkillLearningPolicyStore
	identities ports.OwnerAuthorizationSource
}

func NewSkillLearningPolicyService(store ports.SkillLearningPolicyStore, identities ports.OwnerAuthorizationSource) *SkillLearningPolicyService {
	return &SkillLearningPolicyService{store: store, identities: identities}
}

type SetSkillLearningPolicyInput struct {
	RequestID        string                     `json:"request_id"`
	OrganizationID   string                     `json:"organization_id"`
	AgentID          string                     `json:"-"`
	ActorPrincipalID string                     `json:"actor_principal_id"`
	ExpectedRevision string                     `json:"expected_revision"`
	Mode             string                     `json:"mode"`
	Scope            domain.SkillLearningScope  `json:"scope"`
	PinnedPaths      []string                   `json:"pinned_paths"`
	Limits           domain.SkillLearningLimits `json:"limits"`
}

func (service *SkillLearningPolicyService) Get(ctx context.Context, organizationID, agentID, principalID string) (domain.SkillLearningPolicy, error) {
	scope, err := service.authorize(ctx, organizationID, agentID, principalID)
	if err != nil {
		return domain.SkillLearningPolicy{}, err
	}
	policy, err := service.store.GetSkillLearningPolicy(ctx, scope)
	if err != nil {
		return domain.SkillLearningPolicy{}, mapAgentConfigurationError("read Skill learning policy", err)
	}
	if policy.OrganizationID != organizationID || policy.AgentID != agentID || policy.OwnerPrincipalID != principalID || policy.Validate() != nil {
		return domain.SkillLearningPolicy{}, ErrQueryContract
	}
	return policy, nil
}

func (service *SkillLearningPolicyService) Set(ctx context.Context, input SetSkillLearningPolicyInput) (domain.SkillLearningPolicy, error) {
	if !learningRequestID.MatchString(input.RequestID) || !learningExpectedRevision.MatchString(input.ExpectedRevision) {
		return domain.SkillLearningPolicy{}, ErrInvalidInput
	}
	policy := domain.SkillLearningPolicy{
		OrganizationID: input.OrganizationID, AgentID: input.AgentID, OwnerPrincipalID: input.ActorPrincipalID,
		Revision: input.ExpectedRevision, Mode: input.Mode,
		Scope:       domain.SkillLearningScope{AutoGeneratedPersonal: input.Scope.AutoGeneratedPersonal, AdoptedPaths: slices.Clone(input.Scope.AdoptedPaths)},
		PinnedPaths: slices.Clone(input.PinnedPaths), Limits: input.Limits,
	}
	slices.Sort(policy.Scope.AdoptedPaths)
	slices.Sort(policy.PinnedPaths)
	if err := policy.ValidateMutation(); err != nil {
		return domain.SkillLearningPolicy{}, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	scope, err := service.authorize(ctx, input.OrganizationID, input.AgentID, input.ActorPrincipalID)
	if err != nil {
		return domain.SkillLearningPolicy{}, err
	}
	result, err := service.store.SetSkillLearningPolicy(ctx, ports.SetSkillLearningPolicy{Scope: scope, RequestID: input.RequestID, ExpectedRevision: input.ExpectedRevision, Policy: policy})
	if err != nil {
		return domain.SkillLearningPolicy{}, mapAgentConfigurationError("set Skill learning policy", err)
	}
	return result, nil
}

func (service *SkillLearningPolicyService) authorize(ctx context.Context, organizationID, agentID, principalID string) (ports.SkillLearningPolicyScope, error) {
	if !validIdentifier(organizationID) || !validIdentifier(agentID) || !validIdentifier(principalID) || service.store == nil {
		return ports.SkillLearningPolicyScope{}, ErrInvalidInput
	}
	agent, err := service.store.GetAgent(ctx, agentID)
	if errors.Is(err, ports.ErrNotFound) {
		return ports.SkillLearningPolicyScope{}, ErrAccessDenied
	}
	if err != nil {
		return ports.SkillLearningPolicyScope{}, fmt.Errorf("read Skill learning policy Agent: %w", err)
	}
	if agent.AgentID != agentID || agent.OrganizationID != organizationID || agent.OwnerUserID != principalID ||
		agent.IdentityRevoked() || agent.DesiredState == domain.DesiredDeleted || agent.LifecycleState == domain.AgentDeleted {
		return ports.SkillLearningPolicyScope{}, ErrAccessDenied
	}
	if service.identities == nil {
		return ports.SkillLearningPolicyScope{}, ErrDependencyUnavailable
	}
	owner, err := service.identities.ResolveOwnerAuthorization(ctx, organizationID, principalID)
	if identityReferenceMissing(err) {
		return ports.SkillLearningPolicyScope{}, ErrAccessDenied
	}
	if err != nil {
		return ports.SkillLearningPolicyScope{}, fmt.Errorf("%w: resolve Skill learning policy owner", ErrDependencyUnavailable)
	}
	if owner.UserID != principalID || owner.OrganizationID != organizationID || !owner.Active ||
		strings.TrimSpace(owner.MembershipID) == "" || owner.LastRevocationSequence < 0 ||
		owner.LastRevocationSequence != agent.OwnerAuthorizationSequence {
		return ports.SkillLearningPolicyScope{}, ErrAccessDenied
	}
	return ports.SkillLearningPolicyScope{OrganizationID: organizationID, AgentID: agentID,
		OwnerPrincipalID: principalID, AccessRevision: agent.AccessRevision,
		OwnerRevocationSequence: owner.LastRevocationSequence}, nil
}
